### ISSUE TITLE
Behavior with multiple base images

### ISSUE THREAD

**Issue by Logic1ne** [Marvinho/InformatiCupUndCupper#20]
How does the system behave given multiple base Images?
For now it seems to overwrite some of the solutions?

**Comment by Marvinho** [comment]
one solution would be issue #15 
there are several problems with more than one base image:
- the method moveUsedImage moves every image to the usedImage folder
- limit of the blackbox is 60img/min (since we usually test for 43 labels this will be a problem)

**Comment by Marvinho** [comment]
- For now it seems to overwrite some of the solutions?

a naive approach would be to add seconds to the timestamp, but the above-mentioned problems remain
